# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81dfd13c781beedcb6fe74816b2dce947c34973dbfe010981e870b45b16953ea302aebbae96902d3880dd8979a866978bf69563c5959effa5cd532e3b84b41e9

test:
  secret_key_base: 26aeb1ffa7238f7a81a2c62bf40ebf229a3943757449e055a01a26f6b9105ed5b448d16b024e2af0ddaf16ef6b833a8381fb4de01826c4a7b0d93fcf46fc85d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
